name: Deploy React Native Web to Netlify

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      # Step 4: Build the web version of the app
      - name: Build Expo Web
        run: npx expo start --web

      # Step 5: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 6: Deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=web-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
