name: Deploy React Native Web to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Export web build
      - name: Export Web Build
        run: |
          npm install -g expo-cli
          npx expo export -p web

      # Step 5: Verify Web Build Directory
      - name: Verify Web Build Directory
        run: ls -la web-build

      # Step 6: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 7: Deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=web-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Optional: Fallback to expo build:web if export fails
      - name: Fallback Web Build
        if: failure()
        run: |
          expo build:web
          ls -la web-build
